name: .NET Build and Test

on:
  # Keep existing trigger for PRs and pushes
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Add nightly build trigger
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test with coverage
      run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./test/TestResults/coverage.cobertura.xml /p:Threshold=80
      
    - name: Debug output
      run: ls -ao && cd test && ls -ao

    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '**/test/TestResults/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: coveragereport

    - name: Check coverage threshold
      run: |
        if [[ $(grep -o 'line-rate="[0-9.]*"' **/TestResults/coverage.cobertura.xml | grep -o '[0-9.]*' | awk '{ print int($1 * 100) }') -lt 80 ]]; then
          echo "Code coverage is below 80%"
          exit 1
        fi